using System;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson;

namespace openrmf_upload_api.Models
{
    [Serializable]
    public class Artifact
    {
        public Artifact () {
        }

        public DateTime created { get; set; }
        public string rawChecklist { get; set; }

        // if this is part of a system, list that system group ID here
        public string systemGroupId { get; set; }
        public string systemTitle { get; set; }
        public string hostName { get; set;}
        public string stigType { get; set; }
        public string stigRelease { get; set; }
        public string title { get {
            return hostName.Trim() + "-" + stigType.Trim() + "-" + stigRelease.Trim();
        }}
        
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        [BsonDateTimeOptions]
        // attribute to gain control on datetime serialization
        public DateTime? updatedOn { get; set; }

        public Guid createdBy { get; set; }
        public Guid? updatedBy { get; set; }
    }
}